# -*- coding: utf-8 -*-

"""
Django settings for blog_project project.

Generated by 'django-admin startproject' using Django 1.8.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""
import os
import os.path
from os import environ

debug = not environ.get("APP_NAME", "")

if debug:
	MYSQL_DB = 'blogdb'
	MYSQL_USER = 'ren'
	MYSQL_PASS = 'rjianwang'
	MYSQL_HOST_M = '127.0.0.1'
	MYSQL_HOST_S = '127.0.0.1'
	MYSQL_PORT = '3306'
else:
	MYSQL_DB = "db.t1.micro" 
	MYSQL_USER = "rjianwang" 
	MYSQL_PASS = "rjianwang" 
	MYSQL_HOST_M = "aa1k4kzd9mjr5qx.cskejia6pl1r.us-west-2.rds.amazonaws.com" 
	MYSQL_HOST_S = "aa1k4kzd9mjr5qx.cskejia6pl1r.us-west-2.rds.amazonaws.com" 
	MYSQL_PORT = "3306"

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '!pqysku-^@1n-8v5p#wi2(a@#q7jzbxd&jk*uh-iz$@6k22tsf'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['.applinzi.com', ]


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
	'blog',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'blog_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
				os.path.join(BASE_DIR, 'templates'),
			],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
				'blog.views.global_setting'
            ],
        },
    },
]

WSGI_APPLICATION = 'blog_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': MYSQL_DB,
		'USER': MYSQL_USER,
		'PASSWORD' : MYSQL_PASS,
		'HOST': MYSQL_HOST_M,
		'PORT' : MYSQL_PORT,
    }
}
 

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = (
	os.path.join(BASE_DIR, 'static'),
)

CACHES = {
	'default': {
		'BACKEND': 'django.core.cache.backends.locmem.LocMemCache', 
		'LOCATION': 'unique-snowflake', 
	}
}

MEDIA_URL = '/uploads/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'uploads')

# 自定义用户model
AUTH_USER_MODEL = 'blog.User'

# 网站的基本信息配置
SITE_NAME = '聿壬 · 清林夕园'
ADMIN     = '聿壬'
SITE_DESC = 'Technology Inspires Life'
RSS       = ''
ADDRESS   = "Xi'an, Shaanxi, China"
PHONE     = '158-2973-XXX'
MOBILE    = '158-2973-XXX'
EMAIL     = 'rjianwang@foxmail.com'
WEIBO     = 'http://weibo.com/5060021139'

####	# 自定义日志输出信息
####	LOGGING = {
####		'version': 1,
####		'disable_existing_loggers': True,
####		'formatters': {
####			'standard': {
####				'format': '%(asctime)s [%(threadName)s:%(thread)d] [%(name)s:%(lineno)d] [%(module)s:%(funcName)s] [%(levelname)s]- %(message)s'}  #日志格式
####		},
####		'filters': {
####		},
####		'handlers': {
####			'mail_admins': {
####				'level': 'ERROR',
####				'class': 'django.utils.log.AdminEmailHandler',
####				'include_html': True,
####				},
####			'default': {
####				'level':'DEBUG',
####				'class':'logging.handlers.RotatingFileHandler',
####				'filename': 'log/all.log',     #日志输出文件
####				'maxBytes': 1024*1024*5,       #文件大小
####				'backupCount': 5,              #备份份数
####				'formatter':'standard',        #使用哪种formatters日志格式
####			},
####			'error': {
####				'level':'ERROR',
####				'class':'logging.handlers.RotatingFileHandler',
####				'filename': 'log/error.log',
####				'maxBytes':1024*1024*5,
####				'backupCount': 5,
####				'formatter':'standard',
####				},
####			'console':{
####				'level': 'DEBUG',
####				'class': 'logging.StreamHandler',
####				'formatter': 'standard'
####			},
####			'request_handler': {
####				'level':'DEBUG',
####				'class':'logging.handlers.RotatingFileHandler',
####				'filename': 'log/script.log',
####				'maxBytes': 1024*1024*5,
####				'backupCount': 5,
####				'formatter':'standard',
####				},
####			'scprits_handler': {
####				'level':'DEBUG',
####				'class':'logging.handlers.RotatingFileHandler',
####				'filename':'log/script.log',
####				'maxBytes': 1024*1024*5,
####				'backupCount': 5,
####				'formatter':'standard',
####				}
####		},
####		'loggers': {
####			'django': {
####				'handlers': ['default', 'console'],
####				'level': 'DEBUG',
####				'propagate': False
####			},
####			'django.request': {
####				'handlers': ['request_handler'],
####				'level': 'DEBUG',
####				'propagate': False,
####				},
####			'scripts': {
####				'handlers': ['scprits_handler'],
####				'level': 'INFO',
####				'propagate': False
####			},
####			'blog.views': {
####				'handlers': ['default', 'error'],
####				'level': 'DEBUG',
####				'propagate': True
####			},
####		}
####	}
